import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import PizzaCard from '@/components/PizzaCard'
import PizzaList from '@/components/PizzaList'
import StrengthCard from '@/components/StrengthCard'
import StrengthList from '@/components/StrengthList'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Pizza Ordering App</title>
        <meta name='description' content='Generated by Create next app' />
      </Head>
      <main className={styles.mainContainer}>
        <div className={styles.top}>
        <div className={styles.texts}>
          <h1 className={styles.title}>Handmade,<br /> With an Extra<br /> Pinch of <span className={styles.redText}>Love</span></h1>
          <p className={styles.desc}>Our Pizzas, with their irresistible blend of crisp crust, gooey cheese,<br />
            and flavorful toppings, are the epitome of culinary delight.</p>
          <div className={styles.order}>
            <Image src="/images/white-cart.png" alt='' width={24} height={24} />
            <div className={styles.text}>ORDER NOW</div>
          </div>
        </div>
        <div className={styles.imageContainer}>
        <Image src="/images/yellow-background.png" alt='' width={250} height={230}></Image>
        <Image src="/images/pizza1.png" alt='' width={150} height={130}></Image>
        <Image src="/images/pizza2.png" alt='' width={100} height={80}></Image>
        <Image src="/images/pizza-onion.png" alt='' width={50} height={30}></Image>
        </div>
        </div>
        <div className={styles.center}>
        <Image src="/images/pizza3.png" alt='' width={350} height={330}></Image>
        <div className={styles.texts}>
          <h2 className={styles.title2}>Daily fresh and <br /> always tasty</h2>
          <p className={styles.desc}>A universal favorite, these circular creations come<br /> in endless variations to suit every taste bud. </p>
        </div>
        <Image src="/images/pizza-garlic.png" alt='' width={50} height={30}></Image>
        </div>
        <div className={styles.pizzaContainer}>
        <div className={styles.texts}>
          <span className={styles.redText}>Popular Dishes</span>
          <h2 className={styles.title2}>Browse our Menu</h2>
        </div>
        <div className={styles.pizzas}>
        {PizzaList.map((pizza, index) => (
        <PizzaCard key={index} pizza={pizza} className={styles.pizza} />
      ))}
      </div>
      </div>
      <div className={styles.strengthContainer}>
        <span className={styles.redText}>Our Strength</span>
        <h2 className={styles.title2}>Why We Are The Best</h2>
        <div className={styles.strengthDesc}>
        {StrengthList.map((strength, index) => (
        <StrengthCard key={index} strength={strength}/>
      ))}
        </div>
      </div>
      </main>
    </div>
  )}